---
- include_vars: vars.yml

- include_role:
      name: cloudalchemy.grafana
  vars:
    grafana_security:
      admin_password: "{{ admin_password }}"
      admin_user: admin
    grafana_port: 8000
    grafana_domain: "{{ domain }}/grafana"
    grafana_url: "https://{{ domain }}/grafana"
    grafana_auth:
      anonymous:
        org_name: Anonymous
        org_role: Viewer
