---
- include_vars: vars.yml

- name: Get nvm install script
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh
    dest: "{{NVM_TMP_DIR}}"

- name: Changing perm of nvm script
  file: 
    dest: "{{NVM_TMP_DIR}}"
    mode: a+x

- name: Run nvm install script
  shell: "{{NVM_TMP_DIR}}"

- name: Install node
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install v10"
