---
- name: Clone Nodeapps from GitHub
  git:
    repo: https://github.com/max-wittig/NodeApps.git
    dest: /opt/nodeapps
    update: yes
    clone: yes

- name: Build docker image
  docker_image:
    nocache: yes
    path: /opt/nodeapps
    name: nodeapps
    force: yes

- name: Run docker image
  docker_container:
    name: nodeapps
    image: nodeapps
    exposed_ports: 3000
    published_ports: 3000:3000
    detach: yes
