---
- include_role:
    name: node-exporter

- include_role:
    name: cloudalchemy.prometheus
  vars:
    prometheus_web_listen_address: 127.0.0.1:9090
    prometheus_version: 2.3.2
    prometheus_targets:
      node:  # This is a base file name. File is located in "{{ prometheus_config_dir }}/file_sd/<<BASENAME>>.yml"
        - targets:              #
          - localhost:9100    # All this is a targets section in file_sd format
          - localhost:9090
    prometheus_scrape_configs:
      - job_name: "prometheus"    # Custom scrape job, here using `static_config`
        metrics_path: "/metrics"
        static_configs:
        - targets:
          - "localhost:9090"
      - job_name: "node-exporter"
        file_sd_configs:
        - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from `prometheus_targets`
