---
- name: Update and Upgrade system
  apt:
    update_cache: yes
    force_apt_get: yes
    name: "*"
    state: latest
    cache_valid_time: 3600
  become: yes

- name: Install base packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
  become: yes
  with_items:
    - htop
    - tmux
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - nano
    - iftop
    - iotop
    - git
    - wget

- name: Add SSH keys to authorized keys
  authorized_key:
    user: root
    key: "{{ item }}"
    exclusive: true
    state: present
  with_file:
    - files/ssh_keys.txt
